spring:
  datasource:
    url: jdbc:mysql://192.168.1.116:3306/preprojectdb
    username: root
    password: 123456a@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

