spring:
  datasource:
    url: jdbc:mysql://localhost:3306/preprojectdb
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

